update

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,8 +12,8 @@ fi
 echo
 echo "Which mosek version you want to use"
 echo "  1) mosek 8.1"
-echo "  2) mosek 9.0"
-echo "  3) mosek 9.1"
+echo "  2) mosek 9.1"
+echo "  3) mosek 9.2"
 read -p  "Enter a selection (default=3):" mosek_v
 if [ -z $mosek_v ]
 then
@@ -46,30 +46,7 @@ then
         exit 1
     fi
 fi
-if [ $mosek_v -eq 2 ] && ! [ -d mosek/9.0 ]
-then
-    if [ -f mosektoolslinux64x86.tar.bz2 ]
-    then
-        rm mosektoolslinux64x86.tar.bz2
-    fi
-    wget https://download.mosek.com/stable/9.0.97/mosektoolslinux64x86.tar.bz2
-    if [ $? -ne 0 ]
-    then
-        echo  -e "\033[31m Installation Failed. \033[0m"
-        exit 1
-    fi
-    
-    echo "tar -xjf mosektoolslinux64x86.tar.bz2" 
-    
-    tar -xjf mosektoolslinux64x86.tar.bz2
-    make -C mosek/9.0/tools/platform/linux64x86/src/fusion_cxx install
-    if [ $? -ne 0 ]
-    then
-        echo  -e "\033[31m Installation Failed. \033[0m"
-        exit 1
-    fi
-fi
-if [ $mosek_v -eq 3 ] && ! [ -d mosek/9.1 ]
+if [ $mosek_v -eq 2 ] && ! [ -d mosek/9.1 ]
 then
     if [ -f mosektoolslinux64x86.tar.bz2 ]
     then
@@ -86,6 +63,29 @@ then
     
     tar -xjf mosektoolslinux64x86.tar.bz2
     make -C mosek/9.1/tools/platform/linux64x86/src/fusion_cxx install
+    if [ $? -ne 0 ]
+    then
+        echo  -e "\033[31m Installation Failed. \033[0m"
+        exit 1
+    fi
+fi
+if [ $mosek_v -eq 3 ] && ! [ -d mosek/9.3 ]
+then
+    if [ -f mosektoolslinux64x86.tar.bz2 ]
+    then
+        rm mosektoolslinux64x86.tar.bz2
+    fi
+    wget https://download.mosek.com/stable/9.2.32/mosektoolslinux64x86.tar.bz2
+    if [ $? -ne 0 ]
+    then
+        echo  -e "\033[31m Installation Failed. \033[0m"
+        exit 1
+    fi
+    
+    echo "tar -xjf mosektoolslinux64x86.tar.bz2" 
+    
+    tar -xjf mosektoolslinux64x86.tar.bz2
+    make -C mosek/9.2/tools/platform/linux64x86/src/fusion_cxx install
     if [ $? -ne 0 ]
     then
         echo  -e "\033[31m Installation Failed. \033[0m"
@@ -110,15 +110,15 @@ then
 fi
 if [ $mosek_v -eq 2 ] 
 then
-    cp  -t ./lib/ ./mosek/9.0/tools/platform/linux64x86/bin/libmosek64.so*  \
-        ./mosek/9.0/tools/platform/linux64x86/bin/libfusion64.a  \
-        ./mosek/9.0/tools/platform/linux64x86/bin/libcilkrts.so.5
-fi
-if [ $mosek_v -eq 3 ] 
-then
     cp  -t ./lib/ ./mosek/9.1/tools/platform/linux64x86/bin/libmosek64.so*  \
         ./mosek/9.1/tools/platform/linux64x86/bin/libfusion64.a  \
         ./mosek/9.1/tools/platform/linux64x86/bin/libcilkrts.so.5
+fi
+if [ $mosek_v -eq 3 ] 
+then
+    cp  -t ./lib/ ./mosek/9.2/tools/platform/linux64x86/bin/libmosek64.so*  \
+        ./mosek/9.2/tools/platform/linux64x86/bin/libfusion64.a  \
+        ./mosek/9.2/tools/platform/linux64x86/bin/libcilkrts.so.5
 fi
 
 if [ $? -ne 0 ]
@@ -129,7 +129,7 @@ fi
 
 if [ $mosek_v -eq 2 ]
 then
-    make mosek90=1
+    make mosek91=1
 fi
 if [ $mosek_v -eq 1 ]
 then
@@ -137,7 +137,7 @@ then
 fi
 if [ $mosek_v -eq 3 ]
 then
-    make mosek91=1
+    make mosek92=1
 fi
 
 if [ $? -ne 0 ]
